services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    container_name: voicevox_engine
    ports:
      - "50021:50021"
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G