[rules]
all = "error"

[analysis]
respect-type-ignore-comments = false
allowed-unresolved-imports = []
replace-imports-with-any = []

[environment]
python-version = "3.14"

[src]
include = ["**"]
respect-ignore-files = true

[terminal]
error-on-warning = true
output-format = "full"
